name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Use Latest Corepack
        run: |
          echo "Before: corepack version => $(corepack --version || echo 'not installed')"
          npm install -g corepack@latest
          echo "After : corepack version => $(corepack --version)"
          corepack enable
          corepack prepare pnpm@9.15.0 --activate
          pnpm --version
      - uses: actions/checkout@v4
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          target: serve
          tags: |
            ghcr.io/developer-overheid-nl/don-site:latest
            ghcr.io/developer-overheid-nl/don-site:${{ github.sha }}
